# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ENG/IMS 171 - Technologies of Self
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A class website for thinking through the history of technologies of the self. 
baseurl: "/techofself" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
github_username:  collinjennings

# Build settings
markdown: kramdown
